language: python
pyton:
 - "2.7"

install: "pip install -r requirements.txt"

before_script:
 - autopep8 -ir *.py
 - flake8 --max-complexity=6 --exclude=*.txt,*.md --max-line-length=200 *.py

script:
 - lettuce test
 - python Test_Figura.py -v
 - coverage run --branch Test_Figura.py
 - coverage report -m

notifications:
 - email:false
